### ISSUE TITLE
unable run the project, getting no such file or directory error

### ISSUE THREAD

**Issue by RakshithNM** [yinkakun/eleventy-duo#7]
I am getting the following error on running the project using `npm run dev`. 
![Screenshot 2021-08-19 at 7 56 26 PM](https://user-images.githubusercontent.com/10560321/130086285-8715c6fa-5507-4f69-9a24-62b311a041d1.png)

**Comment by phhu** [comment]
I have same issue.

**Comment by yinkakun** [comment]
I'm sorry for the late responses, I'll look into this right now.

**Comment by ameybhavsar24** [comment]
Following.

**Comment by strigona** [comment]
I believe the issue is that with a clean repo, the `public` directory does not exist and when you run `yarn dev` it tries building the assets and launching the site in parallel. The `dev:site` script fails because the `dev:assets` wasn't able to create the assets files fast enough. I believe the work-around is to manually run `yarn dev:assets` to prime the repo before running `yarn dev`.

**Comment by RakshithNM** [comment]
@brleinad thanks for the tip

**Comment by brleinad** [comment]
No worries @RakshithNM, I have opened a a [PR](https://github.com/yinkakun/eleventy-duo/pull/10) with a fix for this.

**Comment by RakshithNM** [comment]
@brleinad nice, thank you

**Comment by yinkakun** [comment]
Thanks for the fix @RakshithNM
